networks:
  proxynet:
    name: ${PROXY_NAME}
    external: true

services:
  app:
    container_name: {IMAGE_NAME}
    image: {IMAGE_NAME}:{IMAGE_VERSION}
    mem_limit: 512m
    pull_policy: build
    restart: always
    build:
      context: .
      args:
        NEXT_PUBLIC_CONTACT_MAIL: ${NEXT_PUBLIC_CONTACT_MAIL}
        GOOGLE_VERIFICATION_KEY: ${GOOGLE_VERIFICATION_KEY}
        AUTO_TRACK_ENABLED: ${AUTO_TRACK_ENABLED}
        TRACKING_API_HOST: ${TRACKING_API_HOST}
        TRACKING_API_KEY: ${TRACKING_API_KEY}
      tags:
        - {IMAGE_NAME}:{IMAGE_VERSION}
        - {IMAGE_NAME}:latest
    networks:
      - proxynet
