name: '🛡️ Lint and Verify'
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  lint:
    name: '🔍 Setup and Linting'
    runs-on: ubuntu-latest
    steps:
      - name: '📥 Code Checkout'
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: '⚙️ Run CI Setup & Verify'
        uses: ./.github/actions/ci-setup
